In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
arr = np.array(lista)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr

array([1, 6, 3, 4, 5, 6, 7, 8, 9])

In [18]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
matriz[0]

array([1, 2, 3])

In [20]:
matriz[0,2]

3

In [21]:
arr

array([1, 6, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[1:6]

array([6, 3, 4, 5, 6])

In [24]:
arr[-1]

9

In [25]:
 matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])