In [27]:
import numpy as np

In [29]:
arr = np.array([1,2,3,4])
arr.dtype


dtype('int64')

In [30]:
arr = np.array([1,2,3,4], dtype='float64')
arr.dtype


dtype('float64')

In [31]:
arr

array([1., 2., 3., 4.])

In [32]:
arr = np.array([1, 2, 3, 4])
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

In [33]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [36]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [37]:
arr = np.array(['0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)