In [38]:
import numpy as np

In [39]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [40]:
vector = np.array([1, 2, 3])
print(vector)
vector.ndim


[1 2 3]


1

In [41]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [44]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

## Agregar o eliminar dimensiones

In [45]:
vector = np.array([1, 2, 3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [46]:
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [49]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


## ### **Reto**

1. Definir un tensor de 5 dimensiones
2. Sumar una dimensión en algún eje
3. Borrar dimensiones que no se usen

In [50]:
tensor5 = np.array([[[[1, 2],[3, 4]], [[5, 6],[7, 8]]], [[[1, 2],[3, 4]], [[5, 6],[7, 8]]]], ndmin = 5)
print(tensor5, tensor5.ndim)

[[[[[1 2]
    [3 4]]

   [[5 6]
    [7 8]]]


  [[[1 2]
    [3 4]]

   [[5 6]
    [7 8]]]]] 5


In [51]:
expand5 = np.expand_dims(tensor5, axis=1)
print(expand5, expand5.ndim)

[[[[[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]


   [[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]]]] 6


In [52]:
print(expand5, expand5.ndim)
reduced5 = np.squeeze(expand5)
print(reduced5, reduced5.ndim)

[[[[[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]


   [[[1 2]
     [3 4]]

    [[5 6]
     [7 8]]]]]] 6
[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]] 4
