In [69]:
import numpy as np

In [70]:
arr = np.random.randint(1,10,(3,2))

In [71]:
arr.shape

(3, 2)

In [72]:
arr

array([[5, 6],
       [1, 8],
       [2, 6]])

In [73]:
arr.reshape(1,6)

array([[5, 6, 1, 8, 2, 6]])

In [74]:
arr.reshape(2,3)

array([[5, 6, 1],
       [8, 2, 6]])

In [75]:
np.reshape(arr,(1,6))

array([[5, 6, 1, 8, 2, 6]])

In [76]:
arr

array([[5, 6],
       [1, 8],
       [2, 6]])

In [77]:
np.reshape(arr,(2,3),'C')

array([[5, 6, 1],
       [8, 2, 6]])

In [78]:
np.reshape(arr,(2,3),'F')

array([[5, 2, 8],
       [1, 6, 6]])

In [79]:
np.reshape(arr,(2,3),'A')

array([[5, 6, 1],
       [8, 2, 6]])

## RETO
Crear un array de cualquier dimesnión y cambiar sus dimensiones Intentar cambiar el array de forma que no respete la estructura original 1.

In [80]:
array_original = np.random.randint(0,10, (3,3))
array_original

array([[9, 3, 5],
       [1, 5, 9],
       [8, 9, 3]])

In [81]:
array_original.reshape(2,4)

ValueError: cannot reshape array of size 9 into shape (2,4)