In [123]:
import numpy as np

In [142]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [147]:
indices_cond =arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [149]:
arr[0]

1

In [150]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [151]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [153]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [155]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [156]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)