In [54]:
import numpy as np

La siguiente, es la forma como generamos un rango de números en python.


In [55]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Y así lo hacemos con Numpy

In [56]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.zeros(3)

array([0., 0., 0.])

In [59]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [60]:
np.ones((10, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [63]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
np.random.rand()

0.6186798216853212

In [65]:
np.random.rand(4)

array([0.40379842, 0.08240038, 0.24715925, 0.84336161])

In [66]:
np.random.rand(4,4)

array([[0.37434601, 0.16298978, 0.93796698, 0.80889016],
       [0.59800024, 0.8071898 , 0.14518033, 0.66209581],
       [0.3790905 , 0.98961506, 0.93845066, 0.94027403],
       [0.51881696, 0.71311522, 0.25691364, 0.32929101]])

In [67]:
np.random.randint(1,15)

12

In [68]:
np.random.randint(1,100,(10,10))

array([[12, 73, 85, 44, 95, 81, 95, 12, 66, 31],
       [51, 57, 47, 34, 47, 75, 80, 34, 32, 33],
       [98, 94, 61, 57,  4, 91, 91, 83, 96, 57],
       [15, 27, 75, 43, 10, 45, 77, 16, 71, 56],
       [79, 26, 76, 55, 27, 96,  7, 42, 28,  9],
       [ 5, 66,  6, 56, 22, 58, 34, 73,  4, 15],
       [65,  9, 84, 65, 97, 62, 11, 56,  1, 18],
       [59, 68, 55, 72,  6, 34, 37,  4, 32, 68],
       [63, 91, 63, 97, 17, 84, 47, 65, 26, 81],
       [82, 50, 83, 19, 13, 96, 57, 95, 62, 34]])