In [123]:
import numpy as np

In [134]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
trozo_de_arr = arr[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [136]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [137]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [138]:
arr_copy =arr.copy()


In [139]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [140]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])